config/routes.rb
Ecoursereview::Application.routes.draw do
  resource :users
  resources :courses do
     resources :course_reviews do
         resources :users
    end 
  end
  resource :course_reviews
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'courses#index'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/review/new/:slug', to: 'course_reviews#new'
  match "/subject/:subject" => "courses#subject"
  match "/provider/:provider" => "courses#provider"
  match "/:provider/:slug" => "courses#show"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    EduScore ©2012
  </small>
  <nav>
    <ul>
      <li><a href="http://natashatherobot.com/" target="_blank">NatashaTheRobot</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_googleanalytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32457917-1']);
  _gaq.push(['_setDomainName', 'eduscore.co']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "EduScore", root_path, id: "logo" %>
	  	<nav>
			<ul class="nav pull-right">
				<% if signed_in? %>
					<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
				<% else %>
					<li><%= link_to "Sign in", signin_path %></li>
				<% end %>
			</ul>	
		</nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %> 
	<%= render 'layouts/googleanalytics' %>
  </head>
  <body>
     <%= render 'layouts/header' %>
	   <div class="container">
			<% flash.each do |key, value| %>
			  <div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
	     	<%= yield %>
		</div>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
  </body>
</html>